### ISSUE TITLE
Internal Zend error

### ISSUE THREAD

**Issue by codearachnid** [julienbechade/acf-location-field#1]
When I enabled both address and coordinates in the field setup and saved the field grouping I encountered the following error. 

> Fatal error: Internal Zend error - Missing class information for in /var/www/richmondfamilymagazine/www.richmondfamilymagazine.com/wp-content/plugins/advanced-custom-fields-location/location-field.php on line 415

**Comment by julienbechade** [comment]
Sorry, been really busy...

Do you still encounter the same error or is it fixed?
This is obviously some sort of conflict.

**Comment by julienbechade** [comment]
Apparently fixed…

**Comment by jonesch** [comment]
I am still having the same issue with the error. It doesn't show up all the time, but sort of at random. Sometimes it shows up while I am in the back end, and sometimes it shows up on the front end. I am having an issue on Line 499 though. And I grabbed the latest copy of the plugin from your Repo.

Any thoughts??
Thanks!

**Comment by ghost** [comment]
I had the same issue a while ago and got rid of it by adding the following line to my `.htaccess` file:

```
php_flag apc.cache_by_default Off
```

Or if that doesn't do the trick you can also add the next two lines to your `apc.ini` file

```
apc.filters = wp-cache-config
apc.include_once_override = 0
```

**Comment by julienbechade** [comment]
I've look around too and it seems to be quite commun to get this error with Zend…
Have you tried @timhuisman's fix?

**Comment by avocadesign** [comment]
I'm having the same issue 

PHP Fatal error:  Internal Zend error - Missing class information for  in /Users/brendyn/Sites/AvocaDesign/WordPress-Master/wp-content/plugins/advanced-custom-fields-location-field-add-on/location-field.php on line 415

Turning off APC in MAMP PRO sorted it out as did the php_flag apc.cache_by_default Off trick mentioned above.

**Comment by julienbechade** [comment]
@avocadesign Thanks for documenting the error and work around!
