### ISSUE TITLE
Multiple Markers on Same Map?

### ISSUE THREAD

**Issue by demo38** [julienbechade/acf-location-field#10]
Thank you for the Add-On - I was wondering if there was a way to add multiple markers to a single map? Ideally, 2 different marker types?

**Comment by julienbechade** [comment]
No, not at the moment and I don't really plan on developing it. Plus, I want to keep it pretty basic. But you could easily build on it…
Elliot plan on integrating this field to the ACF core in a near future so I don't want to make any further change.
