### ISSUE TITLE
Bug: Problem with Adress and Coordinates

### ISSUE THREAD

**Issue by cybermania** [julienbechade/acf-location-field#11]
Hello,

I'm having some problems with Google-maps location addon.

I want to get only coordinates on frontend, without street address. I tried everything, and everytime i got street address. I'm using <?php the_field('location'); ?> , in my case <?php the_field('lokacija'); ?>

Here is a screenshoot with field settings on the beckend:
![Backend](http://img16.imageshack.us/img16/1431/7d15c97b2ab54bda8d519c1.png)

And here is the placemark in the post.
![Backend](http://img708.imageshack.us/img708/935/65cc619a7c024eeeb73ec2f.png)

My full query in the code is (inside img tag):

```
http://maps.googleapis.com/maps/api/staticmap?center=<?php the_field('lokacija');?>&zoom=15&size=270x140&maptype=roadmap&markers=color:purple|size:mid|label:N|<?php the_field('lokacija');?>&sensor=false
```

and returned value on the frontend is:

```
http://maps.googleapis.com/maps/api/staticmap?center=Булевар Светог Цара Константина, Niš, Serbia&zoom=15&size=270x140&maptype=roadmap&markers=color:purple|size:mid|label:N|Булевар Светог Цара Константина, Niš, Serbia&sensor=false
```

you can notice that, there is only street address, without coordinates.

I also tried your code for returning only coordinates, but without any luck:

```
<?php
$location = get_field('location');

echo $location['address'];
echo $location['coordinates'];
?>
```

Thanks in advance Julien.
Dusan

**Comment by cybermania** [comment]
On the backend in the ACF field settings when i check "Map address - Return the address along with the coordinates." to "YES" then on the frontend i got coordinates too with address (just to note, when i select NO i receive only address without coordinates).

**Comment by cybermania** [comment]
Ok, i have done this successful. 
I used again echo $location['coordinates'];?> .

The reason why i didn't make it work before is because on the settings page  "Map address - Return the address along with the coordinates." i have checked "NO" because i don't need street address. This way i lost array, so $location and $address couldn't work. Also, i thought i will get only coordinates when i use get_field as noted on the ACF addon page, but no, i got street address.

**Comment by julienbechade** [comment]
Sorry for the late answer…
Happy you could fix it.

Cheers.

**Comment by chrisvanpatten** [comment]
FYI, this is definitely a bug. `get_field()` and `the_field()` return addresses, not coordinates. I can't pin down why this is happening, but if I figure out a reason I'll most certainly report it here.

**Comment by driesvints** [comment]
@julienbechade This issue should definitely still be open because the bug isn't fixed as Chris pointed out. Cybermania just fixed it with work-around.

I'm experiencing the same problem. When setting Map Address to "no", the plugin returns the address by default instead of the coordinates.

This error should be fixed or the documentation and plugin info next to the Map Adress option needs to be changed because otherwise it'll continue to create confusion.
