### ISSUE TITLE
Linking to stylesheet incorrectly

### ISSUE THREAD

**Issue by l3rady** [julienbechade/acf-location-field#13]
For some reason your plugin is loading the stylesheet at an incorrect place. Here is where you are trying to load it:

`http://geraldeve.dev.philosophydesign.com/core/C:/wamp/DEV/GeraldEve/wp-content/plugins/advanced-custom-fields-location-field-add-on/style.css?ver=3.5`

I install WordPress in a sub directory set-up very similar to what is out lined at: http://davidwinter.me/articles/2012/04/09/install-and-manage-wordpress-with-git/

Because the core files are in a sub-directory it seems to confuse your code where you try to work out

$this->base_dir, $this->base_uri_rel and $this->base_uri_abs

Your code seems very complex just to work out directories. Have you consider using a WordPress function that uses http://codex.wordpress.org/Function_Reference/plugins_url

**Comment by l3rady** [comment]
Changing:

`wp_register_style( 'acf-location-field', $this->base_uri_abs . '/style.css' );`

to:

`wp_register_style( 'acf-location-field', plugins_url( 'style.css' , __FILE__ ) );`

Sorts the issue out for me and then make all of this code redundant:

```
            //Base directory of this field
    $this->base_dir = rtrim( dirname( realpath( __FILE__ ) ), DIRECTORY_SEPARATOR );

    //Build the base relative uri by searching backwards until we encounter the wordpress ABSPATH
    //This may not work if the $base_dir contains a symlink outside of the WordPress ABSPATH
    $root = array_pop( explode( DIRECTORY_SEPARATOR, rtrim( realpath( ABSPATH ), DIRECTORY_SEPARATOR ) ) );
    $path_parts = explode( DIRECTORY_SEPARATOR, $this->base_dir );
    $parts = array();

    while( $part = array_pop( $path_parts ) ) 
    {
        if( $part == $root )
            break;
        array_unshift( $parts, $part );
    }

    $this->base_uri_rel = '/' . implode( '/', $parts );
    $this->base_uri_abs = get_site_url( null, $this->base_uri_rel );
```

**Comment by chrisvanpatten** [comment]
This! This is a lot of wasted code when there's a simple built-in function that can handle it. (And work better too. I also had bugs.)

**Comment by julienbechade** [comment]
Merged!
