### ISSUE TITLE
Editing location from the front end

### ISSUE THREAD

**Issue by ticktockdesign** [julienbechade/acf-location-field#16]
Hi there - love this plugin, it's been really useful.  

I'm allowing users to edit their content via front-end forms - following the tutorial found here: 

http://www.advancedcustomfields.com/docs/tutorials/creating-a-front-end-form/

When I do that, the map is not displayed - although the address and co-ordinates are. Indeed, when I inspect the element, it does appear to be generating the code associated with the map, just that the map is not displaying.

Do you know why / have you come across this before?

Many thanks in advance for any advice you might have.

David

**Comment by julienbechade** [comment]
This add-on only output address and coordinates by default in the front-end. No map. Never.

**Comment by ticktockdesign** [comment]
Fair enough Julien!  Thanks. It displays the map okay in wp-admin - are there different issues with displaying it on the front end?  Thanks for your response.

---

David Horn
Web Design & Development
www.TickTockDesign.com (http://www.TickTockDesign.com)

e. david@ticktockdesign.com (mailto:david@ticktockdesign.com)
t. +44 (0) 28 66 44 80 90

t. +353 (1) 524 0984

**Comment by julienbechade** [comment]
If you want a map to be displayed in the front-end, you'll need to implement it yourself…
This add-on return only values entered in the admin. No map. Sorry.

**Comment by ticktockdesign** [comment]
No problem - thanks again.

---

David Horn
Web Design & Development
www.TickTockDesign.com (http://www.TickTockDesign.com)

e. david@ticktockdesign.com (mailto:david@ticktockdesign.com)
t. +44 (0) 28 66 44 80 90

t. +353 (1) 524 0984

**Comment by andrewlaskey** [comment]
Add the styles from the plugins style.css to your site stylesheet. That worked for me.

**Comment by julienbechade** [comment]
@andrewlaskey Could you provide a link, please… I'm really interested to check how you made it possible.

**Comment by andrewlaskey** [comment]
No problem.

I used it on my site CampChaser.com. (Still in development. Also you have to create an account to have access to the map edit page.)

Here's what I did. Not a whole lot going on.
https://gist.github.com/andrewlaskey/4997169

I just followed ACF's tutorial on making a front-end form and added your plugin's stylesheet to my site's stylesheet. If you happen to login into my site and see the live version, you'll see I still have to fix up those styles a bit, but the map shows and the form works.

Thanks again for this plugin. I was using geo mashup and it was just a pain trying to customize it.

**Comment by ticktockdesign** [comment]
Huh. I tried that before but with no joy - I'll take another look though - thanks for the follow up.

**Comment by julienbechade** [comment]
@andrewlaskey You're welcome. Happy it can help.
So it's that easy to get it in the front-end then. Did you have to touch the JS or everything worked out of the box?

**Comment by andrewlaskey** [comment]
It worked right out of the box. I could probably do a bit to customize the form or this or that, but yeah, it was that easy.

**Comment by julienbechade** [comment]
Well, that's good to know.
I had no idea you could do that with ACF and it would pulled out and load everything attached to the field.

@ticktockdesign Here you go. Hope you can make it with the info above…
