### ISSUE TITLE
[acf 3.3.8, 3.3.9] Uncaught SyntaxError: Unexpected token ; post.php:1306 Uncaught TypeError: Cannot read property 'value' of null 

### ISSUE THREAD

**Issue by wujekbogdan** [julienbechade/acf-location-field#2]
Map is not shown.
JS console:
Uncaught SyntaxError: Unexpected token ; post.php:1306 Uncaught TypeError: Cannot read property 'value' of null.

Tested on Chrome and FF.

**Comment by julienbechade** [comment]
Sorry, been really busy...

This is a strange error you got there. I was not able to reproduce it.
Do you still have this problem?

**Comment by julienbechade** [comment]
Absolutely no problem w/ the newer version of ACF neither…
