### ISSUE TITLE
Get separate locations

### ISSUE THREAD

**Issue by ayottepl** [julienbechade/acf-location-field#21]
Is there any way to get these locations "separately"?

I would like to use the "meta itemprop" latitude and longitude.. soo i'm not sure. I can probably achieve it with javascript, but i thought it's not the better way to do this :)

Thanks

**Comment by julienbechade** [comment]
You don't need to use javascript for this.
At [that line](https://github.com/julienbechade/acf-location-field/blob/master/location-field.php#L367) do this:

``` php

// format value
$value = explode('|', $value);
$value = explode(',' $value);
if ($field['val'] == 'address') 
{
    $value = array( 
        'address' => $value[0], 
        'latitude' => $value[1], 
        'longitude' => $value[2], 
        'coordinates' => $value[1] . ',' . $value[2]
    );
}
else {
    $value = array( 
        'latitude' => $value[1], 
        'longitude' => $value[2], 
        'coordinates' => $value[1] . ',' . $value[2]
    );
}

// return value
return $value;

```

This code is not tested, but it's what I would do on the top on my head…
