### ISSUE TITLE
maps disappear

### ISSUE THREAD

**Issue by ghost** [julienbechade/acf-location-field#23]
Sometimes, on creating a new post with this field, the maps disappear (gray background). This seems not to be due loading issues, the upper left still shows a small clipping area when navigating trough the map field. I've found a workaround for this, just resize your browser and everything works fine. Maybe not a bug of location field, but google maps itself.

My System:
- Macbook Pro 15" retina
- Mac OS X Mountain Lion 10.8.2
- Safari Version 6.0.2 (8536.26.17)

**Comment by julienbechade** [comment]
Could you post a screenshot?

**Comment by ghost** [comment]
![screenshot](https://f.cloud.github.com/assets/1057526/188951/2d0358ee-7e26-11e2-96ec-05e362f7157a.png)

**Comment by julienbechade** [comment]
Yes, it is GM script.
Part of the map is not being loaded here…

**Comment by h3sands** [comment]
I'm having the same problem, sometimes map is ok, sometimes not. Reloading the page makes it draws fine

Mac OS X 10.6.8
Safari, FF, Chrome

**Comment by julienbechade** [comment]
Nothing I can do about that unfortunately.
Works fine for me.
