### ISSUE TITLE
Display value within input during edit?

### ISSUE THREAD

**Issue by anthonybruno** [julienbechade/acf-location-field#24]
Any thoughts on displaying the value within the input field if a user decides to edit a post or page where your field might be present? 

I mention this because it currently does not and if you declare the input as required and then make an edit to that page, since the field is empty it throws a validation error.

Thoughts?

**Comment by julienbechade** [comment]
The input showed is not the one used to save the data.
[The real field](https://github.com/julienbechade/acf-location-field/blob/master/location-field.php#L277), the one that send the location to the DB when you update the post, is hidden and populated dynamically.
So it doesn't matter if the input is empty as long as the hidden field is not.

It does work as expected for me but you're not the first one to report this problem so it might be something to investigate further.

Could you reproduce the error on post _update_ and then inspect the value of this hidden field?
So we make sure that it's not empty…

**Comment by anthonybruno** [comment]
My instance is working as you described. Input is just the placeholder on update and the hidden input does have the correct value. However it stil throws the validation error.

![Screen Shot 2013-02-23 at 5 23 22 PM](https://f.cloud.github.com/assets/429837/188808/386eb9dc-7e10-11e2-9a16-7323c7f2d477.png)

**Comment by julienbechade** [comment]
Thanks!

I don't know what to say… This is very strange.
The validation should be done on the hidden field as it is the one registered in ACF.

Do you have DEBUG enabled?

**Comment by julienbechade** [comment]
Got it!

You have the Wordpress plugin repo version.
The hidden field [should come first](https://github.com/julienbechade/acf-location-field/blob/master/location-field.php#L277) as the validation check is made on the first field by ACF. I don't know why…

Edit the plugin and you should be fine.

**Comment by anthonybruno** [comment]
That did the trick! I assume that this would be something that would be included in any updates? 

Thanks for the help and for making a great add-on.

**Comment by julienbechade** [comment]
Thanks. Happy to help.

Well, .svn and I aren't so good friends…
I'll push a new version when I have some time. But you better watch this repo instead…
