### ISSUE TITLE
Repeater x location fields: problem with map loading 

### ISSUE THREAD

**Issue by arthurse** [julienbechade/acf-location-field#28]
![repeater-location-fields](https://f.cloud.github.com/assets/3887401/267629/a396a98c-8ea9-11e2-9c90-726bab9273c8.jpg)
i'm using repeater field with location addon, when click "add row" at post editing the repeater adds new map (location) row but the map doesnt load correctly. the map seems "broken", only when i reload the page (updating or publishing the post) the map gets to work fine. the text input for address doesnt work well too. look at the attached image. Is there a solution for this? The repeater x location are compatibles?

**Comment by elliotcondon** [comment]
This issue can be fixed by using a jQuery event to initialize the google map.

Take a look at the js/input/date-picker.php for the event! You can use it like this:

``` javascript
(function($){


    /*
    *  acf/setup_fields
    *
    *  @description: 
    *  @since: 3.5.8
    *  @created: 17/01/13
    */

    $(document).live('acf/setup_fields', function(e, postbox){

        $(postbox).find('.my-div').each(function(){

            // add google map to .my-div

        });

    });


})(jQuery);
```

**Comment by julienbechade** [comment]
It needs to be fixed on the next version…

**Comment by torounit** [comment]
https://gist.github.com/Toro-Unit/5213223

**Comment by elliotcondon** [comment]
Hi @julienbechade 

How are you going with this one? Want a hand?

**Comment by julienbechade** [comment]
@elliotcondon This is some ugly code I got there, I'd like to start over for ACF4 but don't have the bloody time to do anything just now. This highly annoys me.

Didn't you want to merge this field into core?

**Comment by julienbechade** [comment]
@Toro-Unit This looks good! Can't you make a pull request?

**Comment by elliotcondon** [comment]
@Toro-Unit 

Do you mind if I use your code to make a v4 compatible taxonomy field? More than happy to include both you and @julienbechade in the credits, but I would like to put my spin on it too!

**Comment by julienbechade** [comment]
Go ahead for my part! Glad it can help…

**Comment by arthurse** [comment]
thanks! worked very well here :)

**Comment by torounit** [comment]
@julienbechade Just sent a pull request. Thanks!

**Comment by torounit** [comment]
@elliotcondon ACF is Great Plugin! Of cource, You can use my code. I am happy to contribute to the ACF.

**Comment by julienbechade** [comment]
Merged!
