### ISSUE TITLE
How do I actually get the map on the front end?

### ISSUE THREAD

**Issue by jotapee** [julienbechade/acf-location-field#35]
Hi, I'm trying to understand how this plugin works. I have installed with no problems, setup, on the front pageusing <?php the_field('location');?> it returns the values of the coordinates or city, etc (depending how I setup).

I have read all the documentation, but I can't find a way to display the map on frontend, not sure if it's even any? 

If the chance to show the map isn't possible, and plugin only returns the coordinates, what should I do in order to display the map? Should I place like an empty iframe and have the coordinates as a variable being filled by the_field ?

Thanks in advance and sorry for bothering.

**Comment by loru88** [comment]
It is normal, the plugin is intended for save just the coordinates in a custom field; in the front end you have to implements by yourself the google maps api and use the saved coordinates as a map options.
see here:
https://developers.google.com/maps/documentation/javascript/tutorial#MapOptions

**Comment by jotapee** [comment]
Thank you! It would be great that this information could be included on the plugin's documentation just like that. "This plugin does not and won't show a map on frontend, to develop such functionality please follow the link..." etc.
Thanks again.
