### ISSUE TITLE
Display Map on Front End

### ISSUE THREAD

**Issue by woody24** [julienbechade/acf-location-field#39]
I saw some posts that talk about the cordanents are only stored in the backend, and its up to us to figure out how to put it in the maps API.

But the readme.txt file has code that makes it sound like its for the front end. But when I put this is, it still doesn't show. The plugin is activated. What do I need to change to the code below to make it work?

<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>

<script>
    var map;
    var myLatLang = new google.maps.LatLng( <?php  $location = get_field('location'); echo $location['coordinates']; ?>);
    function initialize() {
        var mapOptions = {
            zoom: 8,
            center: myLatLang,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);
        var marker = new google.maps.Marker({
            position: myLatLang,
            map: map,
            title:"Hello World!"
        });
    };
    google.maps.event.addDomListener(window, 'load', initialize);
    $('.bxslider').bxSlider({
        minSlides: 5,
        maxSlides: 5,
        slideWidth: 192,
        slideMargin: 0,
        adaptiveHeight: true
    });
</script>

<div id="map-canvas"></div>

**Comment by woody24** [comment]
Ok. how do you paste code? Anyway, its the same code in the readme file of the plugin.

**Comment by fanchrobin** [comment]
Same for me. Code provided in readme.txt doen't work.
And the geocoder on the Admin doesn't work either. Please help ! Thanx

**Comment by woody24** [comment]
I figured it out. The area in the code called "location" needs to be set to whatever you named your maps field in the backend of wordpress. And I also had to set a height on the ID #map-canvas. 

Took me 3 hours just to figure that out. I'm no PHP coder, just a hacker.

**Comment by fanchrobin** [comment]
Thank you for your quick answer. Yes, I had changed the fierld name in the code, but the point was to set a height for the div id map-canvas.

The geocoder button in the admin back-end doen't work either. Would you any clue to fix that ? 

Cheers,

**Comment by woody24** [comment]
That, I've got no clue on.

**Comment by julienbechade** [comment]
This plugin is no longer developed or supported. Download the version hosted by Elliot, the author of ACF:
https://github.com/elliotcondon/acf-location-field

Elliot should integrate this field into ACF in the next release…
