### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Autocomplete' of undefined

### ISSUE THREAD

**Issue by ghost** [julienbechade/acf-location-field#40]
Running the latest version of the plugin, I encounter this error when including it in either  panel type in WP admin. The plugin is used on posts that feature tabs, as well as the  ACF plugins Repeater Field, Flexible Content and Gallery.

**Comment by julienbechade** [comment]
This plugin is not in development anymore.
Elliot, the author of ACF have integrated it to core.
