### ISSUE TITLE
Be fair

### ISSUE THREAD

**Issue by codeforest** [julienbechade/acf-location-field#5]
Very nice add-on.

It would also be nice to mention that the idea and the first version of the add-on were created by me, and maybe link to me from documentation.

Best regards
Zvonko Biskup
http://codeforest.net

**Comment by julienbechade** [comment]
I even didn't think about that.
I needed it for a project and yourth didn't fit the purpose so I wrote one on the fly from scratch.
But I can totally mention that it was based on your version, which is the truth!

So thanks for your add-on!

**Comment by julienbechade** [comment]
Done!
