### ISSUE TITLE
Map not displayed on Options page

### ISSUE THREAD

**Issue by tx0min** [julienbechade/acf-location-field#6]
The map is not displayed on the options page. 

In function admin_print_styles()  you should change this line:

if( in_array( $pagenow, array( 'post.php', 'post-new.php' ) ) ) 

for this:

if( in_array( $pagenow, array( 'post.php', 'post-new.php', 'admin.php') ) ) 

You can also rmove the conditional clause 

Or maybe there is a better solution

Cheers!

**Comment by julienbechade** [comment]
Sorry for the late answer…

Yes that's right, I actually didn't think of the possibility to add it to an option page.
I wanted to prevent the loading of the script on every single admin page.

Thanks for the feedback.

Cheers.

**Comment by chrisvanpatten** [comment]
Umm... so this is still a bug... and you closed the issue, but didn't fix the code?

**Comment by julienbechade** [comment]
Yeah, sorry about that…
Thought I would have the time to fix it right away, got busy and then forgot about it.
My bad.

**Comment by julienbechade** [comment]
Merged too!
